GamePickerWeb/Areas/Admin/Controllers/GameModelController.cs
using GamePickerDataAccess.Data;
using GamePickerDataAccess.Repository.IRepository;
using GamePickerModels.Models;
using GamePickerModels.ViewModels;
using GamePickerUtility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GamePickerWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class GameModelController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public GameModelController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork= unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }
    public IActionResult Index()
    {
        List<GameModel> objGameModelList = _unitOfWork.GameModelRepository.GetAll(includeItems:"Category").ToList();
        return View(objGameModelList);
    }

    public IActionResult Upsert(int? id)
    {
        IEnumerable<SelectListItem> Categories = _unitOfWork.CategoryRepository.GetAll().Select(u=> new SelectListItem
        {
            Text = u.Name,
            Value = u.Id.ToString()
        });

        GameModelVM gameModelVm = new()
        {
            Categories = Categories,
            GameModel = new GameModel()
        };
        if (id == null || id == 0)
        {
            return View(gameModelVm);
        }
        else
        {
            gameModelVm.GameModel = _unitOfWork.GameModelRepository.Get(u => u.Id == id);
            return View(gameModelVm);
        }
            
    }
    [HttpPost]
    public IActionResult Upsert(GameModelVM gameModelVm, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(wwwRootPath, @"images/gameModel");

                if (!string.IsNullOrEmpty(gameModelVm.GameModel.ImageUrl))
                {
                    var oldImagePath = Path.Combine(wwwRootPath, gameModelVm.GameModel.ImageUrl.TrimStart('/'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                
                using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                gameModelVm.GameModel.ImageUrl = @"/images/gameModel/" + fileName;
            }

            if (gameModelVm.GameModel.Id == 0)
            {
                _unitOfWork.GameModelRepository.Add(gameModelVm.GameModel);
            }
            else
            {
                _unitOfWork.GameModelRepository.Update(gameModelVm.GameModel);
            }
            _unitOfWork.Save();
            TempData["success"] = "GameModel created successfully";
            
            return RedirectToAction("Index");
        }
        else
        {
            gameModelVm.Categories = _unitOfWork.CategoryRepository.GetAll().Select(u=> new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(gameModelVm);
        }
    }

    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    { 
        List<GameModel> objGameModelList = _unitOfWork.GameModelRepository.GetAll(includeItems:"Category").ToList();
        return Json(new { data = objGameModelList });
    }
    
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var deleteGameModel = _unitOfWork.GameModelRepository.Get(u => u.Id == id);
        if (deleteGameModel == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }
        
        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, deleteGameModel.ImageUrl.TrimStart('/'));

        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        
        _unitOfWork.GameModelRepository.Remove(deleteGameModel);
        _unitOfWork.Save();
        
        return Json(new { success = true, message = "Delete successful" });
    }

    #endregion
}

GamePickerWeb/Areas/Admin/Views/GameModel/Delete.cshtml
@model GamePickerModels.Models.GameModel
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-primary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">New GameModel</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <div class="border p-3 mt-4">
                <div class="mb-3 row">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="Publisher"></label>
                    <input asp-for="Publisher" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="RegularPrice"></label>
                    <input asp-for="RegularPrice" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="Price50"></label>
                    <input asp-for="Price50" disabled class="form-control">
                </div>
                <div class="mb-3 row">
                    <label asp-for="Price100"></label>
                    <input asp-for="Price100" disabled class="form-control">
                </div>
                <div class="row">
                    <div class="col-3">
                        <button type="submit" class="btn btn-outline-primary form-control">Delete</button>
                    </div>
                    <div class="col-3">
                        <a asp-controller="GameModel" asp-action="Index" class="btn btn-secondary form-control">
                            Return
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

GamePickerWeb/Areas/Admin/Views/GameModel/Index.cshtml
@model List<GamePickerModels.Models.GameModel>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-primary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-6">
                <h2 class="text-white py-2">Categories</h2>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="GameModel" asp-action="Upsert" class="btn btn-outline-secondary">
                    <i class="bi bi-plus-lg"></i> New GameModel
                </a>
            </div>      
        </div>
    </div>
    <div class="card-body p-4">
        <table id="tableData" class="table table-info table-striped">
            <thead>
            <tr>
                <td>Title</td>
                <td>RegularPrice</td>
                <td>Publisher</td>
                <td>Category</td>
                @* <th></th> *@
            </tr>
            </thead>
        </table> 
    </div>
</div>

@section Scripts
{
    <script src="~/js/gameModel.js"></script>
}

GamePickerWeb/Areas/Admin/Views/GameModel/Upsert.cshtml
@model GameModelVM

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-primary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.GameModel.Id!=0?"Update":"New") GameModel</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" enctype="multipart/form-data">
            <input asp-for="GameModel.Id" hidden />
            <input asp-for="GameModel.ImageUrl" hidden />
            <div class="border p-3">
                <div class="mb-3 row">
                    <img src="@Model.GameModel.ImageUrl" width="50%"/>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Title"></label>
                    <input asp-for="GameModel.Title" class="form-control">
                    <span asp-validation-for="GameModel.Title" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Publisher"></label>
                    <input asp-for="GameModel.Publisher" class="form-control">
                    <span asp-validation-for="GameModel.Publisher" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Description"></label>
                    <textarea asp-for="GameModel.Description" class="form-control"></textarea>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.RegularPrice"></label>
                    <input asp-for="GameModel.RegularPrice" class="form-control">
                    <span asp-validation-for="GameModel.RegularPrice" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Price"></label>
                    <input asp-for="GameModel.Price" class="form-control">
                    <span asp-validation-for="GameModel.Price" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Price50"></label>
                    <input asp-for="GameModel.Price50" class="form-control">
                    <span asp-validation-for="GameModel.Price50" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.Price100"></label>
                    <input asp-for="GameModel.Price100" class="form-control">
                    <span asp-validation-for="GameModel.Price100" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.CategoryId"></label>
                    <select asp-for="GameModel.CategoryId" asp-items="@Model.Categories" class="form-select">
                        <option disabled selected>--Select Category--</option>
                    </select>
                    <span asp-validation-for="GameModel.CategoryId" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="GameModel.ImageUrl"></label>
                    <input type="file" name="file" class="form-control"/>
                </div>
                <div class="row">
                    <div class="col-3">
                        @if (Model.GameModel.Id != 0)
                        {
                            <button type="submit" class="btn btn-outline-primary form-control">Update</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-outline-primary form-control">Create</button>
                        }
                    </div>
                    <div class="col-3">
                        <a asp-controller="GameModel" asp-action="Index" class="btn btn-secondary form-control">
                            Return
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
      tinymce.init({
        selector: 'textarea',
        plugins: 'anchor autolink charmap codesample emoticons lists table visualblocks wordcount',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
      });
    </script>
    @{
        <partial Title="_ValidationScriptsPartial"/>
    }
}